spring.application.name=Food_Delivery_API

# Oracle DB Connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=MYDB9AM
spring.datasource.password=MYDB9AM
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# Hibernate Dialect for Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Auto DDL (choose based on use case)
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL (optional, but useful)
spring.jpa.properties.hibernate.format_sql=true

# SERVER (Embedded Tomcat)
server.port=8761
server.servlet.context-path=/fooddeliveryapi


